### ISSUE TITLE
White space between operand caused index out of bounds

### ISSUE THREAD

**Issue by bartlomiejgora** [bartlomiejgora/RPNLibrary#6]
Input: "1+2 + sin(1)"
Stack trace:

2016-04-02T22:32:00.628375+00:00 app[web.1]: 2016-04-02 22:32:00.627 ERROR 3 --- [nio-4998-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: 0] with root cause
2016-04-02T22:32:00.628426+00:00 app[web.1]:
2016-04-02T22:32:00.628428+00:00 app[web.1]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
2016-04-02T22:32:00.628429+00:00 app[web.1]:    at java.lang.String.charAt(String.java:658) ~[na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628430+00:00 app[web.1]:    at pl.bgora.rpn.FunctionsDefaultChecker.isDigit(FunctionsDefaultChecker.java:40) ~[RPNLibrary-2.0.jar!/:na]
2016-04-02T22:32:00.628447+00:00 app[web.1]:    at pl.bgora.rpn.FunctionsCalculator.createRPN(FunctionsCalculator.java:146) ~[RPNLibrary-2.0.jar!/:na]
2016-04-02T22:32:00.628448+00:00 app[web.1]:    at pl.bgora.rpn.FunctionsCalculator.calculate(FunctionsCalculator.java:44) ~[RPNLibrary-2.0.jar!/:na]
2016-04-02T22:32:00.628449+00:00 app[web.1]:    at pl.bgora.calculator.web.rest.RestCalculatorController.calculate(RestCalculatorController.java:20) ~[classes!/:na]
2016-04-02T22:32:00.628449+00:00 app[web.1]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628450+00:00 app[web.1]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628451+00:00 app[web.1]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628451+00:00 app[web.1]:    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628452+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628453+00:00 app[web.1]:    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628454+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628455+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628461+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628462+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628463+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628464+00:00 app[web.1]:    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628465+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628466+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628466+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628467+00:00 app[web.1]:    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844) ~[spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628468+00:00 app[web.1]:    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628468+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628469+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628469+00:00 app[web.1]:    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628470+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628471+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628476+00:00 app[web.1]:    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628477+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628477+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628478+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628479+00:00 app[web.1]:    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628479+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628480+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628481+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628481+00:00 app[web.1]:    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628482+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628483+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628483+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628484+00:00 app[web.1]:    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628485+00:00 app[web.1]:    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-04-02T22:32:00.628485+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628486+00:00 app[web.1]:    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628486+00:00 app[web.1]:    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628489+00:00 app[web.1]:    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628487+00:00 app[web.1]:    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628489+00:00 app[web.1]:    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628488+00:00 app[web.1]:    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628490+00:00 app[web.1]:    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628487+00:00 app[web.1]:    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628491+00:00 app[web.1]:    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628491+00:00 app[web.1]:    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628492+00:00 app[web.1]:    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628492+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628493+00:00 app[web.1]:    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628494+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628494+00:00 app[web.1]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628497+00:00 app[web.1]:    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-04-02T22:32:00.628498+00:00 app[web.1]:    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74-cedar14]
2016-04-02T22:32:00.628498+00:00 app[web.1]:
2016-04-02T22:32:27.061404+00:00 heroku[router]: at=info method=GET path="/calculate/1+2+sin(1)" host=calculatorweb.herokuapp.com request_id=1a498263-6b4e-47a1-aeaa-89beb483a117 fwd="87.101.22.98" dyno=web.1 connect=1ms service=20ms status=200 bytes=239

**Comment by bartlomiejgora** [comment]
1 + 2 + 3 +sin(1) Works fine.
so the operator must stick to the function (sin here)

**Comment by bartlomiejgora** [comment]
Corrected in FunctionCalculator line 131: 
  if (!lastWasLetter && !lastWasWhiteSpace) {
was   if (!lastWasLetter) {
